site_name: Showdown Documentation
site_description: Showdown is a JavaScript Markdown to HTML converter

theme:
  name: material
  custom_dir: overrides
  logo: https://showdownjs.github.io/apple-touch-icon.png
  favicon: https://showdownjs.github.io/apple-touch-icon.png
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

exclude_docs: |
  requirements.txt

extra:
  drawer_title: Documentation

extra_css:
  - assets/extra.css
  
repo_url: https://github.com/showdownjs/showdown
repo_name: showdownjs/showdown
site_dir: public

nav:
  - Introduction: index.md
  - Quickstart:
    - Quickstart: quickstart.md
    - Markdown to HTML: markdown-to-html.md
    - HTML to Markdown: html-to-markdown.md
    - Integrations: integrations.md
  - Markdown Syntax:
    - Overview: syntax-overview.md
    - Original: original.md
    - Showdown: markdown-syntax.md
    - CommonMark: commonmark.md
    - GFM: gfm.md
  - Configuration:
    - API reference: api-reference.md
    - Flavors: flavors.md
    - Options: options.md
  - CLI: cli.md
  - Extensions:
    - Overview: extensions.md
    - Event system: event-system.md
    - Create an extension: create-extension.md
    - List of known extensions: extensions-list.md
  - Tutorials: tutorials/index.md
  - Security Concerns:
    - XSS vulnerability: xss.md
  - Contributing:
    - Contribution guide: contribution-guide.md
    - Local development: local-development.md
    - Credits: credits.md
